/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface LandRegistryInterface extends utils.Interface {
  functions: {
    "buyLand(uint256,string)": FunctionFragment;
    "getLandDetails(uint256)": FunctionFragment;
    "getLandsByOwner(address)": FunctionFragment;
    "landCount()": FunctionFragment;
    "lands(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "registerLand(string,string,uint256,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "toggleForSale(uint256,uint256)": FunctionFragment;
    "transferOwnership(uint256,address,string)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buyLand"
      | "getLandDetails"
      | "getLandsByOwner"
      | "landCount"
      | "lands"
      | "owner"
      | "registerLand"
      | "renounceOwnership"
      | "toggleForSale"
      | "transferOwnership(uint256,address,string)"
      | "transferOwnership(address)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyLand",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLandDetails",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLandsByOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "landCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lands",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerLand",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleForSale",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership(uint256,address,string)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership(address)",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "buyLand", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLandDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLandsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "landCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lands", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerLand",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleForSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership(uint256,address,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership(address)",
    data: BytesLike
  ): Result;

  events: {
    "LandForSale(uint256,uint256)": EventFragment;
    "LandRegistered(uint256,string,string,uint256)": EventFragment;
    "LandSold(uint256,address,address,uint256)": EventFragment;
    "OwnershipTransferred(uint256,address,address,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LandForSale"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LandRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LandSold"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred(uint256,address,address,string)"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred(address,address)"
  ): EventFragment;
}

export interface LandForSaleEventObject {
  landId: BigNumber;
  price: BigNumber;
}
export type LandForSaleEvent = TypedEvent<
  [BigNumber, BigNumber],
  LandForSaleEventObject
>;

export type LandForSaleEventFilter = TypedEventFilter<LandForSaleEvent>;

export interface LandRegisteredEventObject {
  landId: BigNumber;
  location: string;
  ownerName: string;
  area: BigNumber;
}
export type LandRegisteredEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  LandRegisteredEventObject
>;

export type LandRegisteredEventFilter = TypedEventFilter<LandRegisteredEvent>;

export interface LandSoldEventObject {
  landId: BigNumber;
  from: string;
  to: string;
  price: BigNumber;
}
export type LandSoldEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  LandSoldEventObject
>;

export type LandSoldEventFilter = TypedEventFilter<LandSoldEvent>;

export interface OwnershipTransferred_uint256_address_address_string_EventObject {
  landId: BigNumber;
  from: string;
  to: string;
  newOwnerName: string;
}
export type OwnershipTransferred_uint256_address_address_string_Event =
  TypedEvent<
    [BigNumber, string, string, string],
    OwnershipTransferred_uint256_address_address_string_EventObject
  >;

export type OwnershipTransferred_uint256_address_address_string_EventFilter =
  TypedEventFilter<OwnershipTransferred_uint256_address_address_string_Event>;

export interface OwnershipTransferred_address_address_EventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferred_address_address_Event = TypedEvent<
  [string, string],
  OwnershipTransferred_address_address_EventObject
>;

export type OwnershipTransferred_address_address_EventFilter =
  TypedEventFilter<OwnershipTransferred_address_address_Event>;

export interface LandRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LandRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyLand(
      _landId: PromiseOrValue<BigNumberish>,
      _newOwnerName: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getLandDetails(
      _landId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, BigNumber, boolean, string]>;

    getLandsByOwner(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    landCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    lands(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, boolean, string] & {
        location: string;
        ownerName: string;
        area: BigNumber;
        price: BigNumber;
        isForSale: boolean;
        currentOwner: string;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    registerLand(
      _location: PromiseOrValue<string>,
      _ownerName: PromiseOrValue<string>,
      _area: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    toggleForSale(
      _landId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(uint256,address,string)"(
      _landId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _newOwnerName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buyLand(
    _landId: PromiseOrValue<BigNumberish>,
    _newOwnerName: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getLandDetails(
    _landId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber, BigNumber, boolean, string]>;

  getLandsByOwner(
    _owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  landCount(overrides?: CallOverrides): Promise<BigNumber>;

  lands(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber, boolean, string] & {
      location: string;
      ownerName: string;
      area: BigNumber;
      price: BigNumber;
      isForSale: boolean;
      currentOwner: string;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  registerLand(
    _location: PromiseOrValue<string>,
    _ownerName: PromiseOrValue<string>,
    _area: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  toggleForSale(
    _landId: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(uint256,address,string)"(
    _landId: PromiseOrValue<BigNumberish>,
    _to: PromiseOrValue<string>,
    _newOwnerName: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyLand(
      _landId: PromiseOrValue<BigNumberish>,
      _newOwnerName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getLandDetails(
      _landId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, BigNumber, boolean, string]>;

    getLandsByOwner(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    landCount(overrides?: CallOverrides): Promise<BigNumber>;

    lands(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, boolean, string] & {
        location: string;
        ownerName: string;
        area: BigNumber;
        price: BigNumber;
        isForSale: boolean;
        currentOwner: string;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    registerLand(
      _location: PromiseOrValue<string>,
      _ownerName: PromiseOrValue<string>,
      _area: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    toggleForSale(
      _landId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(uint256,address,string)"(
      _landId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _newOwnerName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "LandForSale(uint256,uint256)"(
      landId?: null,
      price?: null
    ): LandForSaleEventFilter;
    LandForSale(landId?: null, price?: null): LandForSaleEventFilter;

    "LandRegistered(uint256,string,string,uint256)"(
      landId?: null,
      location?: null,
      ownerName?: null,
      area?: null
    ): LandRegisteredEventFilter;
    LandRegistered(
      landId?: null,
      location?: null,
      ownerName?: null,
      area?: null
    ): LandRegisteredEventFilter;

    "LandSold(uint256,address,address,uint256)"(
      landId?: null,
      from?: null,
      to?: null,
      price?: null
    ): LandSoldEventFilter;
    LandSold(
      landId?: null,
      from?: null,
      to?: null,
      price?: null
    ): LandSoldEventFilter;

    "OwnershipTransferred(uint256,address,address,string)"(
      landId?: null,
      from?: null,
      to?: null,
      newOwnerName?: null
    ): OwnershipTransferred_uint256_address_address_string_EventFilter;
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferred_address_address_EventFilter;
  };

  estimateGas: {
    buyLand(
      _landId: PromiseOrValue<BigNumberish>,
      _newOwnerName: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getLandDetails(
      _landId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLandsByOwner(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    landCount(overrides?: CallOverrides): Promise<BigNumber>;

    lands(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    registerLand(
      _location: PromiseOrValue<string>,
      _ownerName: PromiseOrValue<string>,
      _area: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    toggleForSale(
      _landId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "transferOwnership(uint256,address,string)"(
      _landId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _newOwnerName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyLand(
      _landId: PromiseOrValue<BigNumberish>,
      _newOwnerName: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getLandDetails(
      _landId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLandsByOwner(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    landCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lands(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerLand(
      _location: PromiseOrValue<string>,
      _ownerName: PromiseOrValue<string>,
      _area: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    toggleForSale(
      _landId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(uint256,address,string)"(
      _landId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _newOwnerName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
